#!/usr/bin/env bash
#DESC: T4 — replace the hand-written bindings.conf with a generated one
#
# Golden rule 5: every behaviour change ships a migration.
#
# Before T4, config/hypr/bindings.conf was a hand-written placeholder, shipped
# and seeded once by monarch-config-apply. It is now generated from
# schema/keybinds.toml, and the placeholder is gone from the repository.
#
# Seed-only means monarch-config-apply will not replace the old file, so on a
# machine that installed a pre-T4 checkout the placeholder would sit there
# indefinitely — working, but missing everything T4 added (clipboard history,
# the editor launch, SUPER+/ for the keybind list) and not regenerated by
# anything. This is the trigger.
#
# The old file is kept as bindings.conf.pre-t4 rather than overwritten. It was
# hand-written; if the user edited it, those edits are the only record of what
# they wanted, and transcribing them into keybinds.toml is a two-minute job
# that cannot be done at all once the file is gone.
#
# Idempotent: the backup is only taken if the file is not already generated.

set -euo pipefail

: "${MONARCH_HOME:?migrations run through monarch-migrate; set MONARCH_HOME to run one standalone}"

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
bindings="$config_dir/hypr/bindings.conf"
apply="$MONARCH_HOME/bin/monarch-keys-apply"

[[ -x "$apply" ]] || { printf 'monarch-keys-apply is missing — nothing to do\n'; exit 0; }

if [[ -f "$bindings" ]] && ! head -n1 "$bindings" | grep -q 'GENERATED BY MONARCH'; then
  cp -a "$bindings" "$bindings.pre-t4"
  printf 'kept your old bindings.conf as bindings.conf.pre-t4\n'
  printf 'if you had edited it, transcribe those edits into:\n'
  printf '  %s/monarch/keybinds.toml\n' "$config_dir"
fi

"$apply"
