#!/usr/bin/env bash
#DESC: Stage 40 — greetd, snapper, zram, networking, bluetooth, firewall
#
# Sourced by bootstrap.sh. Safe to re-run: every unit enable is idempotent and
# every config file is compared before it is replaced.

: "${MONARCH_HOME:?install stages run through bootstrap.sh; set MONARCH_HOME to run one standalone}"

# shellcheck source=/dev/null
source "$MONARCH_HOME/install/_common.sh"

stage_40_greetd() {
  info "Configuring greetd + tuigreet"

  write_system_file /etc/greetd/config.toml 0644 <<'EOF'
# GENERATED BY MONARCH — DO NOT EDIT
# Regenerate with: monarch config apply

[terminal]
vt = 1

[default_session]
# SINGLE quotes around the greeting, inside the double-quoted TOML value.
# greetd tokenises this command shell-style, so single quotes group the phrase
# without terminating the TOML string. Double quotes here produce invalid TOML
# and a machine that boots to no login screen at all.
#
# One line only: tuigreet renders the greeting above the login box and clips
# multi-line art rather than wrapping it. The full wordmark goes to /etc/issue
# instead, which is what the TTYs show — see install/45-branding.sh.
command = "tuigreet --greeting 'MonARCH — Arch Linux, made yours.' --time --remember --remember-user-session --asterisks --cmd Hyprland"
user = "greeter"
EOF

  # Deliberately NOT --now. Starting greetd from inside the TTY session that is
  # running this installer would kill the install halfway through.
  enable_unit greetd.service
  ok "greetd will take over at next boot"
}

stage_40_snapper() {
  info "Configuring Snapper"

  if ! have snapper; then
    warn "snapper not installed — skipping snapshot setup"
    return 0
  fi

  if [[ -f /etc/snapper/configs/root ]]; then
    ok "snapper root config already exists"
  else
    # Btrfs layouts vary enough that this legitimately fails on some installs
    # (a pre-existing /.snapshots subvolume is the usual cause). Warn, do not
    # abort: an install without snapshots still boots.
    if sudo snapper -c root create-config /; then
      ok "snapper root config created"
    else
      warn "Could not create the snapper root config."
      warn "Usually means /.snapshots already exists as a subvolume."
      warn "Fix by hand, then run: sudo snapper -c root create-config /"
      return 0
    fi
  fi

  enable_unit snapper-timeline.timer now
  enable_unit snapper-cleanup.timer now
  ok "snapshot timers enabled"
}

stage_40_zram() {
  info "Configuring zram swap"

  # Half of RAM, capped at 8G. On the 32GB EliteBook that is 8G of compressed
  # swap, which is plenty and leaves the page cache alone.
  write_system_file /etc/systemd/zram-generator.conf 0644 <<'EOF'
# GENERATED BY MONARCH — DO NOT EDIT

[zram0]
zram-size = min(ram / 2, 8192)
compression-algorithm = zstd
swap-priority = 100
fs-type = swap
EOF

  ok "zram configured (active after reboot)"
}

stage_40_network() {
  info "Enabling networking and bluetooth"
  enable_unit NetworkManager.service now
  enable_unit bluetooth.service now
  enable_unit systemd-timesyncd.service now
  ok "network services enabled"
}

stage_40_firewall() {
  info "Configuring the firewall"

  if ! have ufw; then
    warn "ufw not installed — skipping firewall setup"
    return 0
  fi

  sudo ufw default deny incoming
  sudo ufw default allow outgoing

  # If this install is happening over SSH, denying incoming without this would
  # cut the connection mid-install.
  if [[ -n "${SSH_CONNECTION:-}" ]]; then
    warn "SSH session detected — allowing incoming SSH so this install can finish"
    sudo ufw allow ssh
  fi

  sudo ufw --force enable
  enable_unit ufw.service
  ok "firewall active: deny incoming, allow outgoing"
}

stage_40_services() {
  stage_40_greetd
  stage_40_snapper
  stage_40_zram
  stage_40_network
  stage_40_firewall
}

stage_40_services
