#!/usr/bin/env bash
#DESC: Stage 45 — make the system identify itself as MonARCH
#
# Sourced by bootstrap.sh. Safe to re-run: every write compares first.
#
# Everything here is cosmetic in the sense that nothing breaks without it, and
# not cosmetic at all in the sense that a machine calling itself "Arch Linux"
# on the login screen is a machine that has not been made into anything.
#
# All of it reads brand/monarch.ascii. Change the art, re-run the stage, and
# the TTY, the login screen and fastfetch all follow.

: "${MONARCH_HOME:?install stages run through bootstrap.sh; set MONARCH_HOME to run one standalone}"

# shellcheck source=/dev/null
source "$MONARCH_HOME/install/_common.sh"

BRAND_ART="$MONARCH_HOME/brand/monarch.ascii"
BRAND_SHARE="/usr/share/monarch"

# --------------------------------------------------------------- the artwork ---

stage_45_install_art() {
  [[ -r "$BRAND_ART" ]] || { warn "no brand/monarch.ascii — skipping branding"; return 1; }

  # A system-wide copy, because /etc/issue and fastfetch are read by things
  # running as other users (agetty as root, fastfetch as anyone) and cannot
  # reach into one user's home.
  info "Installing brand art"
  sudo mkdir -p "$BRAND_SHARE"
  sudo install -m 0644 "$BRAND_ART" "$BRAND_SHARE/monarch.ascii"
  ok "$BRAND_SHARE/monarch.ascii"
}

# -------------------------------------------------------------- /etc/os-release ---

stage_45_os_release() {
  local version="unknown"
  [[ -r "$MONARCH_HOME/version" ]] && version=$(<"$MONARCH_HOME/version")

  info "Identifying the system as MonARCH"

  # On stock Arch, /etc/os-release is a SYMLINK to /usr/lib/os-release, and the
  # `filesystem` package owns both. systemd reads /etc/os-release first and
  # falls back to /usr/lib, so replacing the symlink with a real file is the
  # supported way to rebrand — it is what every Arch derivative does.
  #
  # Two consequences worth knowing:
  #   * pacman still owns /usr/lib/os-release and will keep updating it. Ours
  #     shadows it and is never touched.
  #   * a `filesystem` upgrade may notice /etc/os-release changed and leave a
  #     .pacnew alongside. That is cosmetic; ignore it, or diff it if a future
  #     Arch adds a field worth copying.
  #
  # ID_LIKE=arch is load-bearing, not decoration. bootstrap.sh's own guard
  # accepts ID=arch OR ID_LIKE containing arch, so re-running the installer on
  # a branded system still works — and every third-party script that checks for
  # Arch keeps working for the same reason.
  if [[ -L /etc/os-release ]]; then
    step "replacing the symlink to /usr/lib/os-release with our own file"
    sudo rm -f /etc/os-release
  fi

  write_system_file /etc/os-release 0644 <<EOF
# GENERATED BY MONARCH — regenerate with: install/45-branding.sh
#
# Shadows /usr/lib/os-release, which pacman still owns and still updates.
# ID_LIKE=arch is required: it is what tells bootstrap.sh, the AUR helpers and
# anything else checking for Arch that this is still Arch underneath.

NAME="MonARCH"
PRETTY_NAME="MonARCH ${version}"
ID=monarch
ID_LIKE=arch
BUILD_ID=rolling
VERSION_ID="${version}"
ANSI_COLOR="38;2;124;109;242"
HOME_URL="https://github.com/Johnnycarriere215/MonARCH-Modern-Arch-OS"
DOCUMENTATION_URL="https://github.com/Johnnycarriere215/MonARCH-Modern-Arch-OS/tree/main/docs"
SUPPORT_URL="https://github.com/Johnnycarriere215/MonARCH-Modern-Arch-OS/issues"
BUG_REPORT_URL="https://github.com/Johnnycarriere215/MonARCH-Modern-Arch-OS/issues"
LOGO=monarch
EOF
  ok "os-release: MonARCH ${version}"
}

# ------------------------------------------------------------------ /etc/issue ---

stage_45_issue() {
  [[ -r "$BRAND_ART" ]] || return 0

  info "Branding the console login"

  # /etc/issue is printed by agetty above the login prompt on every TTY. This
  # is what you see on Ctrl+Alt+F2, and what you see if greetd fails — which
  # makes it the one branding surface that shows up precisely when things have
  # gone wrong.
  #
  # agetty treats \ as an escape (\n = hostname, \l = tty). The art contains
  # none, but a future one might, so escape defensively rather than trusting it.
  {
    printf '\n'
    sed 's/\\/\\\\/g' "$BRAND_ART"
    printf '\n'
    printf '  \\S{PRETTY_NAME}  ·  \\l  ·  \\n\n\n'
  } | sudo tee /etc/issue >/dev/null
  sudo chmod 0644 /etc/issue

  ok "/etc/issue"
}

# ------------------------------------------------------------------- greetd ---

stage_45_greeting() {
  local conf=/etc/greetd/config.toml
  [[ -f "$conf" ]] || { step "no greetd config — stage 40 owns that"; return 0; }

  # Deliberately read-only. The greeting is set in stage 40's heredoc, where
  # the file is authored, because sed-ing a quoted string into a quoted TOML
  # value is how you produce a config that parses as nothing and a machine
  # that boots to no login screen.
  #
  # tuigreet's greeting is one line by nature — it renders above the login box
  # and clips multi-line art. The full wordmark is on the TTYs via /etc/issue.
  if grep -q -- '--greeting' "$conf"; then
    ok "login screen greeting set (stage 40)"
  else
    warn "greetd has no greeting — stage 40 did not write the current config"
    step "re-run the installer, or add --greeting to $conf by hand"
  fi
}

# ---------------------------------------------------------------- fastfetch ---

stage_45_fastfetch() {
  have fastfetch || { step "fastfetch not installed — skipping"; return 0; }

  info "Pointing fastfetch at the MonARCH logo"

  # System-wide, so it applies to every user including root. A user who wants
  # something else drops their own config in ~/.config/fastfetch and it wins.
  #
  # The logo is the file installed above rather than fastfetch's built-in
  # "arch" art: this is the one place a person is most likely to screenshot.
  write_system_file /etc/fastfetch/config.jsonc 0644 <<EOF
// GENERATED BY MONARCH — regenerate with: install/45-branding.sh
//
// System-wide default. Your own ~/.config/fastfetch/config.jsonc overrides it.
{
  "\$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": {
    "type": "file",
    "source": "$BRAND_SHARE/monarch.ascii",
    "color": { "1": "35" },
    "padding": { "top": 1, "right": 3 }
  },
  "display": { "separator": "  " },
  "modules": [
    "break",
    { "type": "title", "format": "{user-name}@{host-name}" },
    "separator",
    { "type": "os",         "key": "os     " },
    { "type": "kernel",     "key": "kernel " },
    { "type": "wm",         "key": "wm     " },
    { "type": "shell",      "key": "shell  " },
    { "type": "terminal",   "key": "term   " },
    { "type": "cpu",        "key": "cpu    " },
    { "type": "gpu",        "key": "gpu    " },
    { "type": "memory",     "key": "memory " },
    { "type": "disk",       "key": "disk   " },
    { "type": "uptime",     "key": "uptime " },
    { "type": "packages",   "key": "pkgs   " },
    "break",
    "colors"
  ]
}
EOF
  ok "/etc/fastfetch/config.jsonc"
}

stage_45_branding() {
  stage_45_install_art || return 0
  stage_45_os_release
  stage_45_issue
  stage_45_greeting
  stage_45_fastfetch
}

stage_45_branding
